// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC86p01rNpDu4OY7HFtdGmUVJyo3HXMs9g',
    appId: '1:638475175038:web:943185f1470b56a22c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    authDomain: 'learnfirebase-76a04.firebaseapp.com',
    storageBucket: 'learnfirebase-76a04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu7qVBKNmksyFhYc2t9ERp4JnbcNe1hdQ',
    appId: '1:638475175038:android:7fb31d8d889ded552c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    storageBucket: 'learnfirebase-76a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJM-eSgSdaZQp0M1bBKgM1rpzrRdmjOYU',
    appId: '1:638475175038:ios:d611e596a68afbcf2c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    storageBucket: 'learnfirebase-76a04.appspot.com',
    iosClientId:
        '638475175038-hoelhuuc2cpn3dvvh2h5juh5ejb3bjcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ylupi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJM-eSgSdaZQp0M1bBKgM1rpzrRdmjOYU',
    appId: '1:638475175038:ios:d611e596a68afbcf2c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    storageBucket: 'learnfirebase-76a04.appspot.com',
    iosClientId:
        '638475175038-hoelhuuc2cpn3dvvh2h5juh5ejb3bjcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ylupi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC86p01rNpDu4OY7HFtdGmUVJyo3HXMs9g',
    appId: '1:638475175038:web:485183580adce7b22c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    authDomain: 'learnfirebase-76a04.firebaseapp.com',
    storageBucket: 'learnfirebase-76a04.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC86p01rNpDu4OY7HFtdGmUVJyo3HXMs9g',
    appId: '1:638475175038:web:fbb1bc0becdc0b462c042f',
    messagingSenderId: '638475175038',
    projectId: 'learnfirebase-76a04',
    authDomain: 'learnfirebase-76a04.firebaseapp.com',
    storageBucket: 'learnfirebase-76a04.appspot.com',
  );
}
